import Navbar from '@/components/Navbar'
import './globals.css'
import { Nunito } from 'next/font/google'

const inter = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + ' bg-slate-100'}>
        <div className=' max-w-[1000px] mx-auto min-h-screen'>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  )
}
